// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Entry struct {
	ID uuid.UUID `json:"id"`
	// URL domain
	Domain string `json:"domain"`
	// login/user field content
	Login sql.NullString `json:"login"`
	// hashed password
	Password string `json:"password"`
	// date of creation
	Created time.Time `json:"created"`
	// date of last update
	Updated time.Time      `json:"updated"`
	Meta    sql.NullString `json:"meta"`
}
